title: Blog (GitHub Pages+Jekyll)
author: Shayan Ahmed
email: my.email@mail.com
description: > # this means to ignore newlines until "baseurl:"
  This Blog is hosted by GitHub Pages and made using Jekyll.
  Hope you enjoy it :D

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
